import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: 'Next App Project',
  description: 'Generated by create next app',
}
const vazirFont = localFont({
  src:'../../public/fonts/Vazirmatn-Regular.woff2'
})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa">
      <body className={vazirFont.className}>{children}</body>
    </html>
  )
}
